### PR TITLE
server/wallet: dont decode op_return_message

### PR DESCRIPTION
**Pull request by octobocto**
See https://github.com/LayerTwo-Labs/cusf_sidechain_proto/pull/28 for motivation and why this is necessary.

### CODE REVIEW

**Comment by torkelrogstad** [comment]
Don't think this is a good idea!

**Comment by octobocto** [comment]
> Don't think this is a good idea!

How else can I pass raw bytes to the op-return output?

**Comment by torkelrogstad** [comment]
I don't understand what you're saying here. The code as-is allows you to send raw bytes just fine. If you do this: 

```
$ buf curl  -d '{..., "op_return_message": {"hex": "deadbeef"}}' ... SendTransaction
```

That's going to end up as `Vec(0xde, 0xad, 0xbe, 0xef)` (i.e. raw bytes!), NOT as the string "deadbeef" in the final OP_RETURN message.

**Comment by octobocto** [comment]
> I don't understand what you're saying here. The code as-is allows you to send raw bytes just fine. If you do this:
> 
> ```
> $ buf curl  -d '{..., "op_return_message": {"hex": "deadbeef"}}' ... SendTransaction
> ```
> 
> That's going to end up as `Vec(0xde, 0xad, 0xbe, 0xef)` (i.e. raw bytes!), NOT as the string "deadbeef" in the final OP_RETURN message.

I want to send `this is the embedded message`, and have that message be embedded. That does not work with the existing implementation.

**Comment by torkelrogstad** [comment]
Then the correct thing to do is to decode that string into raw bytes, and then hex-encode those raw bytes. 

```go
hex.EncodeToString([]byte("this is the embedded message"))
``

Dunno the Rust equivalent off the top of my head, i'm sure chatgpt does

**Comment by torkelrogstad** [comment]
Can this be closed?

**Pull request closed without merging**
